<a href="https://colab.research.google.com/github/pranavkerkar31/AI-ML/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Reshape


In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
# reshaped2=reshaped.reshape(3,2)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

Reval

In [9]:
ravel = arr.ravel()
ravel          # cpnvert the array to 1-D

array([1, 2, 3, 4, 5, 6])

Indexing

In [14]:
arr=np.array([1,2,3,4,5])
print(arr[-1])
print(arr[3])

4
4


Slicing

In [26]:
array=np.array([10,20,30,40,50])
array[: :2]

array([10, 30, 50])

MultiDimension

In [30]:
arr = np.array([[1,2,3],
               [4,5,6],
                [7,8,9]])
# arr[0:2, 0:3]
arr[1:, 1:]

array([[5, 6],
       [8, 9]])