<a href="https://colab.research.google.com/github/pranavkerkar31/AI-ML/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Views vs Copy

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
view=arr[1:3]
view

array([2, 3])

In [5]:
view[0]=200
view # the original array also changes
arr

array([  1, 200,   3,   4,   5])

In [7]:
copy=arr[1:3].copy()
copy
copy[0]=20
arr

array([  1, 200,   3,   4,   5])

Transpose

In [12]:
arr=np.array([[1,2,3],[4,5,6]])
arr.transpose()


array([[1, 4],
       [2, 5],
       [3, 6]])

Swapaxes

In [19]:
arr=np.array([[[1,2],[3,4]]])
print(arr.shape)
swap=np.swapaxes(arr,0,1)
print(swap.shape)



(1, 2, 2)
(2, 1, 2)


Concatenation

In [24]:
a=np.array([1,2])
b=np.array([3,4])
print(np.concatenate((a,b))) # 1 row vector
print(np.vstack((a,b)))  # vertical line
print(np.hstack((a,b)))

[1 2 3 4]
[[1 2]
 [3 4]]
[1 2 3 4]


Repeating

In [25]:
arr=np.array([1,2,3])
print(np.repeat(arr,2))

[1 1 2 2 3 3]


Tile

In [27]:
# repeats the whole array
print(np.tile(arr,2))

[1 2 3 1 2 3]


Sum, Mean, Median, Standard Deviation, Variance, Min

In [34]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
print("Sum:", np.sum(matrix, axis=0)) # axis 0 means the coloumn and 1 means the row.
print("Mean:", np.mean(matrix))
print("Median:", np.median(matrix))
print("Standard Deviation:", np.std(matrix))
print("Variance:", np.var(matrix))
print("Min:", np.min(matrix))
print("Max:", np.max(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum: [12 15 18]
Mean: 5.0
Median: 5.0
Standard Deviation: 2.581988897471611
Variance: 6.666666666666667
Min: 1
Max: 9


Cummulative Operation

In [36]:
print(np.cumsum(arr)) # its 1, 1+2, 1+2+3
print(np.cumprod(arr))

[1 3 6]
[1 2 6]
