<a href="https://colab.research.google.com/github/pranavkerkar31/AI-ML/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dimension

In [3]:
import numpy as np
arr = np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

Range

In [ ]:
#for lists
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
# Numpy
arr = np.arange(1,10,3) # start end step
print(arr)

[1 4 7]


In [ ]:
# arr = np.linspace(0,1,6) # equla spacing of the numbers between a range
# arr

# arr = np.zeros(6)
arr = np.zeros([2,3], dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# matriz of our choice
# arr=np.full([2,3],7)

# arr = np.random.rand(2,5)

# arr = np.random.randn(2,4) # random floats from standard normal distribution
arr=np.random.randint(20,50,size=(2,3))
arr

array([[39, 45, 29],
       [24, 46, 21]])

Type


In [10]:
import numpy as np
arr=np.array([1,2,35,56], dtype=np.float64) # data type conversion
arr.dtype # to check the data type

dtype('float64')

Type Casting

In [15]:
arr=np.array([1,2,3])
arr.dtype  # default dtype is int64 for integer numbers
newarr=arr.astype(np.float64) # astype to convert the type
newarr

array([1., 2., 3.])

Type Casting Error

In [20]:
arr=np.array([[1,2,3],
               [4,5,6]])
arr.ndim
arr.shape
arr.size

6