<a href="https://colab.research.google.com/github/pranavkerkar31/AI-ML/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Dimension

In [1]:
import numpy as np
arr = np.array([[[]]])
arr.ndim
arr.shape

(1, 1, 0)

Range

In [23]:
#for lists
for i in range(10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [30]:
# Numpy
arr = np.arange(1,10,3) # start end step
print(arr)

[1 4 7]


In [36]:
# arr = np.linspace(0,1,6) # equla spacing of the numbers between a range
# arr

# arr = np.zeros(6)
arr = np.zeros([2,3], dtype=int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

In [8]:
# matriz of our choice
# arr=np.full([2,3],7)

# arr = np.random.rand(2,5)

# arr = np.random.randn(2,4) # random floats from standard normal distribution
# arr=np.random.randint(20,50,size=(2,3))
# arr
arr=np.random.randint(10,30,size=(1,2,3))
arr

array([[[12, 11, 10],
        [22, 12, 19]]])